# Geyser Configuration File
# 
# A bridge between Minecraft: Bedrock Edition and Minecraft: Java Edition.
# 
# GitHub: https://github.com/GeyserMC/Geyser
# Discord: https://discord.gg/geysermc
# Website: https://geysermc.org/

# Bedrock server settings
bedrock:
  # The IP address that will listen for connections.
  # Generally, you should only uncomment and change this if you want to limit what IPs can connect to your server.
  #address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
  # If either of these are empty, either the respective string will be used, or if that is also empty, "Geyser" will be used
  motd1: "Minecraft Fabric Server"
  motd2: "Java & Bedrock Edition Support"
  # The Server Name that will be sent to Minecraft: Bedrock Edition clients. This is visible in both the pause menu and the settings menu.
  server-name: "Fabric 1.21.7 Server"
  # How much to compress network traffic to the Bedrock client. The higher the number, the more CPU usage used, but
  # the smaller the bandwidth used. Does not have any effect below -1 or above 9. Set to -1 to disable.
  compression-level: 6
  # Whether to enable proxy protocol or not for clients. You DO NOT WANT this feature unless you are running behind a proxy like nginx or Apache.
  enable-proxy-protocol: false

# Remote server settings for the Java server Geyser will connect to
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # and for plugin versions, Geyser will attempt to find the best address to connect to.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: floodgate

# Floodgate uses encryption to ensure use from authorised sources.
# This should point to the public key generated by Floodgate (BungeeCord, Spigot or Velocity)
# You can ignore this when not using Floodgate.
# If you're using a plugin version of Floodgate on the same server, the key will automatically be picked up from Floodgate.
floodgate-key-file: floodgate/key.pem

# The Xbox/Minecraft: Bedrock Edition username is the key for the Java server to store its information in.
# This is how you can see who is online!
# "username" - use the Minecraft: Bedrock Edition username
# "uuid" - use the Minecraft: Bedrock Edition UUID
# "xuid" - use the Minecraft: Bedrock Edition XUID
saved-user-logins:
  - xuid
  - uuid

# For offline authentication systems (where online-mode is false), Geyser needs to cache and track UUIDs.
# This should not be a problem unless you're using an offline authentication plugin like AuthMe.
# You can ignore this when not using an offline authentication plugin.
# Changing this setting will overwrite any existing cache; keep it as "global" if you don't know what this setting does.
pending-authentication-timeout: 120

# Whether to use a direct connection to the Java server without creating a TCP connection.
# This should only be disabled if a plugin that interfaces with packets or the network does not work correctly with Geyser.
# If enabled on plugin versions, the remote address and port sections are ignored.
# If disabled on plugin versions, expect performance decrease and latency increase.
use-direct-connection: true

# Forward the hostname that the Bedrock client used to connect over to the Java server
# This is designed to be used for forced hosts on proxies
forward-hostname: false

# Whether to pass the MOTD and max player count from the Java server to Bedrock players
passthrough-motd: true
passthrough-protocol-name: true
passthrough-player-counts: true
legacy-ping-passthrough: false

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

# Geyser updates the Scoreboard after every Scoreboard packet, but when Geyser tries to handle
# a lot of scoreboard packets per second can cause serious lag.
# This option allows you to specify after how many milliseconds Geyser will update the Scoreboard for Bedrock clients.
# Increase this value if you're having performance issues with Geyser and scoreboards.
scoreboard-packet-threshold: 20

# Allow connections from ProxyPass and Waterdog.
# See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
enable-proxy-connections: false

# The MTU that will be used by Geyser. This should be a reliable number and should not be changed unless you know what you're doing.
mtu: 1400

# If debug mode is enabled, information useful for developers will be printed.
debug-mode: false

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
# default-locale: en_us

# Configures if chunk caching should be enabled or not. This keeps an individual
# record of each block the client loads in. This feature does allow for a few things
# such as canceling block break/place events. However, this also requires a good amount
# of memory, so only enable if you truly need it.
# Be aware that non-vanilla blocks will not be cached and some alternate behaviors may occur.
cache-chunks: false

# Specify how many days images will be cached to disk to save downloading them from the internet.
# A value of 0 is disabled. Default is 0.
cache-images: 0

# Bedrock prevents building and displaying blocks above Y127 in the Nether -
# enabling this config option works around that by changing the Nether dimension ID
# to the End ID. The main downside to this is that the sky will resemble that of the End sky in the Nether.
# Please note that this is a global setting, and that the Nether and End dimensions in-game may not work if this is changed.
# The End will need to be disabled in server.properties and a plugin will be needed to handle this.
# Requires a restart.
above-bedrock-nether-building: false

# Force clients to load all resource packs if there are any.
# If set to true, it will disconnect the client if a resource pack is not loaded successfully.
# This is useful if you want to force the client to use a specific resource pack.
force-resource-packs: false

# Allow custom skulls to be displayed. Keeping them enabled may cause a performance decrease on older/weaker devices.
allow-custom-skulls: true

# The maximum number of custom skulls to be displayed per player. 0 = no limit.
max-visible-custom-skulls: 128

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Geyser usage. You can learn more about bStats here: https://bstats.org/.
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: generateduuid-here