# Production configuration for Geyser
# Optimized for high-performance cross-play

bedrock:
  address: 0.0.0.0
  port: 19132
  clone-remote-port: false
  motd1: "MOITM Production Server"
  motd2: "High-Performance Cross-Play"
  server-name: "MOITM Production"
  compression-level: 8
  enable-proxy-protocol: false
  proxy-protocol: false

remote:
  address: 127.0.0.1
  port: 25565
  auth-type: floodgate

floodgate-key-file: config/floodgate/key.pem
use-adapters: true
usernames-must-be-ascii: false

usernames:
  replace-spaces: true

# Performance optimizations for production
debug-mode: false
general-thread-pool: 64

# Security settings
allow-third-party-capes: false
allow-third-party-ears: false

# Performance settings
show-cooldown: true
show-coordinates: false
disable-bedrock-scaffolding: true
emote-offhand-workaround: "disabled"

# Cache settings for production
cache-images: 7
allow-custom-skulls: false
above-bedrock-nether-building: false

# Metrics enabled for monitoring
metrics:
  enabled: true
  uuid: generateduuid

# Production performance settings
scoreboard-packet-threshold: 50
enable-proxy-connections: true
mtu: 1400
use-direct-connection: true

config-version: 4