# Floodgate Configuration File
# 
# This is the configuration file for Floodgate.
# GitHub: https://github.com/GeyserMC/Floodgate

# Configuration version. DO NOT CHANGE!
config-version: 2

# Username prefix for Bedrock Edition players
# This is used to differentiate between Java and Bedrock Edition players
username-prefix: "."

# Whether to replace spaces in Bedrock Edition usernames with underscores
replace-spaces: true

# Whether to replace illegal characters in Bedrock Edition usernames
replace-illegal-characters: true

# The default language to be used for Floodgate
default-language: en_us

# The key file path. This should be the path to the key.pem file
key-file-name: key.pem

# Whether to send debug messages
debug: false

# Whether to disconnect players with invalid data/data that couldn't be verified
disconnect-invalid-players: true

# Metrics (bStats) settings
player-link:
  # Whether to link Java Edition accounts with Bedrock Edition accounts
  enabled: true
  # The database type to use for storing linked accounts
  # Options: sqlite, mysql
  type: sqlite
  # SQLite database settings (only used if type is sqlite)
  sqlite:
    # The path to the SQLite database file
    database: floodgate_database.db
  # MySQL database settings (only used if type is mysql)
  mysql:
    # The host of the MySQL server
    host: localhost
    # The port of the MySQL server
    port: 3306
    # The database name
    database: floodgate
    # The username for the MySQL server
    username: root
    # The password for the MySQL server
    password: ""
    # Additional connection properties
    properties:
      useSSL: false
      autoReconnect: true