# ViaFabric Configuration
# 
# This configuration enables client version compatibility
# Allows older Minecraft clients to connect to the 1.21.7 server

# Whether to enable ViaVersion
enable-protocol-translation: true

# The minimum supported client version
# Set to the oldest version you want to support
# Format: major.minor.patch (e.g., 1.20.0)
minimum-supported-version: "1.19.0"

# Protocol translation settings
protocol:
  # Enable backwards compatibility
  enable-backwards: true
  
  # Enable forwards compatibility (experimental)
  enable-forwards: false
  
  # Debug mode for troubleshooting
  debug: false

# Client compatibility
client-support:
  # Support for different client types
  java-clients: true
  
  # Version range support
  version-range:
    min: "1.19.0"
    max: "1.21.7"

# Performance settings
performance:
  # Cache translated packets for better performance
  enable-packet-cache: true
  
  # Maximum cached packets per player
  max-cached-packets: 1000

# Logging
logging:
  # Log client connections with version info
  log-connections: true
  
  # Log protocol translation events
  log-translations: false