# Geyser Configuration for MOITM Server
# Cross-platform bridge for Bedrock Edition clients

bedrock:
  # The IP address that will listen for connections
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the port to be the same as your Java port.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients
  motd1: "MOITM Server"
  motd2: "Cross-Play Enabled"
  # The Server Name that will be sent to Minecraft: Bedrock Edition clients
  server-name: "MOITM Advanced Server"
  # How much to compress network traffic to the Bedrock client. The higher the number, the more CPU usage.
  compression-level: 6
  # Whether to enable PROXY protocol or not for clients. You DO NOT WANT this unless you know what you're doing.
  enable-proxy-protocol: false
  # Whether to enable the forwarding of player IPs
  # This is only useful if you're using a proxy like BungeeCord or Velocity in front of Geyser
  proxy-protocol: false

remote:
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: floodgate

# Floodgate uses encryption to ensure use from authorised sources.
# This should match the key configured in Floodgate - see https://github.com/GeyserMC/Geyser/wiki/Floodgate
# You can ignore this when not using Floodgate.
floodgate-key-file: config/floodgate/key.pem

# The Xbox/MCPE username is the key for the Java server instead of the Java UUID.
# This should only be enabled if the `auth-type` is `floodgate`.
use-adapters: true

# Bedrock clients can have longer usernames than Java clients.
# This setting allows the usernames to be truncated down to 16 characters.
usernames-must-be-ascii: false

# For online mode authentication type.
usernames:
  # Replaces spaces in Bedrock usernames with underscores
  replace-spaces: true

# Various performance and debugging options
debug-mode: false
general-thread-pool: 32

# Allow third party capes to be visible. Currently allowing:
# OptiFine capes, LabyMod capes, 5Zig capes and MinecraftCapes
allow-third-party-capes: true

# Allow third party deadmau5 ears to be visible. Currently allowing:
# MinecraftCapes
allow-third-party-ears: false

# Allow a fake cooldown indicator to be sent. Bedrock players do not see a cooldown as they have no indicator for it.
show-cooldown: true

# Controls if coordinates are shown to players.
show-coordinates: true

# Whether Bedrock players are blocked from breaking blocks above the Bedrock world height
disable-bedrock-scaffolding: false

# If set, when a Bedrock player performs any emote, it will swap the offhand and mainhand.
# There are three options this can be set to:
# disabled - the default/fallback, which doesn't apply this workaround
# no-emotes - emotes will NOT be sent to other players
# emotes-and-offhand - emotes will be sent to other players AND the offhand swap will occur
emote-offhand-workaround: "disabled"

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
# default-locale: en_us

# Specify how many days images will be cached to disk to save downloading them from the internet.
cache-images: 0

# Allows custom skulls to be displayed. Keeping them enabled may cause a performance decrease on older/weaker devices.
allow-custom-skulls: true

# Whether to add (at the beginning) the metrics id of this Geyser instance, or if it's the same as the server's metrics id.
add-non-bedrock-items: true

# Whether bedrock players can use an anvil to rename items with formatting codes
above-bedrock-nether-building: false

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Geyser, such as how many people use it and their player count.
# The only thing you get out of disabling it is a warm feeling inside that you made
# a developer sad :( https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: generateduuid

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

# Geyser updates the Scoreboard after every Scoreboard packet, but when Geyser tries to handle
# a lot of scoreboard packets per second, the performance of the server might suffer.
# This option allows you to specify after how many milliseconds a new Scoreboard update should be sent.
# The higher this number is, the less often the Scoreboard will be updated.
# Increase this number if you're having performance issues with many scoreboards.
scoreboard-packet-threshold: 20

# Allow connections from ProxyPass and Waterdog.
# See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
enable-proxy-connections: false

# The internet supports a maximum MTU of 1492 but could cause issues with packet fragmentation.
# 1400 is the default.
mtu: 1400

# Whether or not to use direct server methods to retrieve information such as block states.
use-direct-connection: true

config-version: 4